# Generated by Django 5.2.12 on 2026-03-11 20:06

import User.CustomUserManager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_users_managers_remove_users_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('objects', User.CustomUserManager.CustomUserManager()),
            ],
        ),
    ]
