# Generated by Django 5.2.12 on 2026-03-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKeys',
        ),
        migrations.DeleteModel(
            name='Models',
        ),
        migrations.DeleteModel(
            name='RateLimits',
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
        migrations.DeleteModel(
            name='UsageStats',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
